config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :todos
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, allow_blank: false

  has_many :todos, dependent: :destroy
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    if params[:category_ids].present?
      if params[:category_ids].include?(0)
        @categories = Category.all
      else
        @categories = Category.where(id: params[:category_ids])
      end
    else
      @categories = Category.all
    end
  end

  def create
    @category = Category.create category_params
    redirect_to root_path
  end

  def destroy
    Category.find(params[:id]).destroy
  end
end

private

def category_params
  params.require(:category).permit(:name)
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
    @categories = Category.all
  end

  def create
    @todo = Todo.create todo_params
    redirect_to root_path
  end

  def edit
    @todo = Todo.find(params[:id])
    @categories = Category.all
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update todo_params
    redirect_to root_path
  end

  def destroy
    Todo.find(params[:id]).destroy
    redirect_to root_path
  end

  private

  def todo_params
    params.require(:todo).permit(:content, :completed, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/categories/_category_list.html.erb
<div style="font-size:16px;padding-bottom:8px;">Filter by category</div>
<%= form_tag categories_path, :method=> 'get' do %>
  <div style="padding-bottom:8px;"><%= submit_tag 'Filter' %></div>
  <div class="category-item">
    <div>
      <%= check_box_tag 'show_all', 1 %>
      All
    </div>
  </div>
  <% @categories.each do |category| %>
    <div class="category-item">
      <div>
        <%= check_box_tag 'category_ids[]', category.id %>
        <%= category.name %>
      </div>
      <div class="category-color-swatch" style="background-color:<%= colors[category.id % colors.length] %> "></div>
    </div>
  <% end %>
<% end %>
<div>
  <%= form_for Category.new do |f| %>
      <%= f.text_field :name, placeholder: 'new category' %><br />
  <% end %>
</div>

app/views/categories/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
<% colors = %w(#F97B58 #F2AD6A #ECDA9A #D1EEEA #85C4C9 #4F90A6 #2196F3 #4EBAAA #7CB342 #757575 #FFB300 #FF6F60) %>

<div class="root">
  <div class="grid-container-root">
    <div class="grid-container-root-item">
      <div class="drawer-background">
        <% todos = @categories.map { |category| category.todos }.flatten %>
        <div style="font-size: 16px;">
          ATB Chore Board
        </div>
        <div>
          <div style="font-size: 16px;">
            New Chore
          </div>
          <%= form_for Todo.new do |f| %>
            <%= f.text_area :content %>
            <%= f.select :category_id, @categories.collect{ |c| [c.name, c.id] }%><br><br>
            <%= f.submit "Create"%>
          <% end %>
        </div>
        <div>
          <%= render partial: 'categories/category_list', locals: { colors: colors } %>
        </div>
      </div>
    </div>
    <div class="grid-container-root-item" style="padding:16px;">
      <div class="status-label">In progress</div>
      <div class="todo-container">
        <% todos.each do |todo| %>
          <%= render partial: "todos/todo_item", locals: { todo: todo, colors: colors } unless todo.completed %>
        <% end %>
      </div>
      <div class="status-label">Completed</div>
      <div class="todo-container">
        <% todos.each do |todo| %>
          <%= render partial: "todos/todo_item", locals: { todo: todo, colors: colors } if todo.completed %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo_item.html.erb
<div class="todo-card">
  <%= link_to(todo.content, todo_path(todo.id)) %>
  <% color = colors[todo.category_id % colors.length] %>
  <div style="position:absolute;top:8px;right:8px;">
    <span class="category-chip" style="background-color:<%= color %>"><%= todo.category.name %></span>
    <%= link_to image_tag("check_icon.png",height: 24, width: 24, class: "item-actions"), todo_path(todo, todo: {completed: true}), method: :put %>
    <%= link_to image_tag("edit_icon.png", height: 24, width: 24, class: "item-actions"), edit_todo_path(todo[:id]) %>
    <%= link_to image_tag("delete_new_icon.png", height: 24, width: 24, class: "item-actions"), todo, method: :delete%>
  </div>
</div>

app/views/todos/edit.html.erb
<div style="padding:16px;">
  <h1>Edit your todo</h1>

  <%= form_for @todo do |f| %>
    <%= f.text_area :content %><br />
    <%= f.select :category_id, @categories.collect{ |c| [c.name, c.id] }%>
    <%= f.submit "Update" %>
  <% end %>
</div>

app/views/todos/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

<div class="root">
  <div class="grid-container-root">
    <div class="grid-container-root-item">
      <div class="drawer-background">
        <div style="font-size: 16px;">
          ATB Chore Board
        </div>
        <div>
          <%= button_to("New chore", new_todo_path, :method => :get, :class => 'add-button') %>
        </div>
        <div>
          <%= render partial: 'categories/category_list' %>
        </div>
      </div>
    </div>
    <div class="grid-container-root-item">
      <div class="status-label">In progress</div>
      <div class="todo-container">
        <% @todos.each do |todo| %>
          <%= render partial: "todos/todo_item", locals: {todo: todo} unless todo.completed %>
        <% end %>
      </div>
      <div class="status-label">Completed</div>
      <div class="todo-container">
        <% @todos.each do |todo| %>
          <%= render partial: "todos/todo_item", locals: {todo: todo} if todo.completed %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<h1>Todo Show Page</h1>
<p>Content: <%= @todo.content %></p>
<p>Category: <%= @todo.category.name %></p>
<p>Completed?: <%= !!@todo.completed %></p>

<%= link_to "Back To Todo List", root_path%>